name: codio-publish
on:
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Publish to Codio
        uses: codio/codio-assignment-publish-action@master
        with:
          client-id: ${{ secrets.CODIO_DEMO_CLIENT_ID }}
          secret-id: ${{ secrets.CODIO_DEMO_SECRET_ID }}
          course-id: 004d0c98d345bfa262bfecdd9b510a0d
          assignment-id: dad1b5a4f6a3d5354047e9992ce4c346
          dir: ./
          changelog: ${{ github.event.head_commit.message }}
